### ISSUE TITLE
Name of Organization

### ISSUE THREAD

**Issue by Ashishban** [codescalers/www-codescalers#7]
URL - https://codescalers.com/

Cloud Computing

Incubaid has identified many opportunities for innovation in the IAAS layer.

Should we have Codescaler instead of Incubaid?

<img width="421" alt="12" src="https://user-images.githubusercontent.com/91247662/220144815-fc32f6ea-bb37-4d56-842c-10076723005b.png">

**Comment by ehab-hassan** [comment]
done
